import type { MicroUsdc } from '@tab/money'
import type { RefusalCode } from '@tab/protocol'

/**
 * The wire shapes, and the results a caller sees.
 *
 * Refusal codes and message schemas are **re-exported from `@tab/protocol`,
 * never redefined** — a second copy drifts, and the copy that drifts is always
 * the one a consumer is holding.
 *
 * Amounts cross the wire as **decimal strings** and are parsed to `MicroUsdc`
 * on the way in, because `bigint` does not survive `JSON.stringify`. Every
 * `MicroUsdc` in this file has therefore already been parsed; every string
 * amount is still on the wire.
 */

export type { RefusalCode } from '@tab/protocol'
export { REFUSAL_CODES, REFUSAL_GUIDANCE, isRetryable } from '@tab/protocol'

/* ── spend ──────────────────────────────────────────────────────────────── */

export interface SpendRequest {
  /** The agent's tab. */
  tab: string
  /** The seller's URL, including whatever the seller needs to be paid. */
  url: string
  /** The most this call may cost. */
  max: MicroUsdc
  /**
   * Idempotency key.
   *
   * Generated by the client when absent, so a network retry cannot
   * double-spend — the gateway treats it as the hold id. A caller that retries
   * a `TabUnavailableError` MUST reuse the key it sent, which is why the client
   * returns it even on failure.
   */
  idempotencyKey?: string
  init?: { method?: string; headers?: Record<string, string>; body?: string }
}

export interface SpendPaid {
  outcome: 'paid'
  amount: MicroUsdc
  seller: string
  holdId: string
  /** Sequence number of the debit receipt on the HCS topic. */
  receiptSeq: number | null
  /** The seller's own response body, untouched. */
  body: unknown
  elapsedMs: number
}

export interface SpendRefused {
  outcome: 'refused'
  /** The exact rule that fired. This is the product working, not an error. */
  rule: RefusalCode
  reason: string
  /** What the agent should do next. Handling refusal is its main job. */
  guidance: string
  retryable: boolean
  /** The numbers behind the decision, so a caller can show or log them. */
  evidence?: Record<string, string | number>
}

/**
 * Infrastructure failed AFTER the decision to spend — distinct from a refusal
 * on purpose. A refusal means the rail said no; this means nobody said
 * anything, and the caller does not know whether the seller was paid.
 */
export interface SpendFailed {
  outcome: 'failed'
  reason: string
  holdId: string
}

export type SpendResult = SpendPaid | SpendRefused | SpendFailed

/* ── quote ──────────────────────────────────────────────────────────────── */

/**
 * A pre-flight check that reserves nothing.
 *
 * Separate from `spend` because an agent planning a batch needs to know what it
 * can afford without taking headroom it may not use — and a hold taken by a
 * quote would be a hold that never commits, which is exactly the shape the
 * reconciler has to clean up.
 */
export interface Quote {
  tab: string
  affordable: boolean
  available: MicroUsdc
  ceiling: MicroUsdc
  perCallCap: MicroUsdc
  /** Set when not affordable — the rule that would fire. */
  wouldRefuse?: RefusalCode
  reason?: string
}

/* ── state ──────────────────────────────────────────────────────────────── */

export interface TabState {
  tab: string
  /** Signed. Negative means the agent owes. */
  balance: MicroUsdc
  outstanding: MicroUsdc
  holds: MicroUsdc
  available: MicroUsdc
  ceiling: MicroUsdc
  perCallCap: MicroUsdc
  window: number
  entries: number
}

export interface Hold {
  holdId: string
  counterparty: string
  amount: MicroUsdc
  at: string
  expiresAt: string
  status: 'pending' | 'committed' | 'expired'
}

/* ── receipts ───────────────────────────────────────────────────────────── */

export type ReceiptLeg = 'hold' | 'debit' | 'credit' | 'refusal' | 'repair' | 'settlement'

export interface ReceiptRow {
  leg: ReceiptLeg
  /**
   * The HCS sequence number, when this entry was replayed from a topic.
   *
   * Optional because an entry the gateway created this instant has not been
   * published yet. It is the number to cite in an audit, so the console shows
   * it rather than a counter of its own.
   */
  seq?: number
  /** Hash of the request, when the receipt carried one. Never the request. */
  requestHash?: string
  /** The token these amounts are denominated in. Absent on pre-`tok` receipts. */
  token?: string
  /** Consensus timestamp — the ordering key, and the only one that counts. */
  at: string
  window: number
  counterparty?: string
  /** Signed, as the ledger holds it. */
  amount?: MicroUsdc
  attested?: boolean
  transactionId?: string
  holdId?: string
  rule?: RefusalCode
}
