import type { MicroUsdc } from '@tab/money'
import type { RefusalCode, WeightReason } from '@tab/protocol'

/**
 * The wire shapes, and the results a caller sees.
 *
 * Refusal codes and message schemas are **re-exported from `@tab/protocol`,
 * never redefined** — a second copy drifts, and the copy that drifts is always
 * the one a consumer is holding.
 *
 * Amounts cross the wire as **decimal strings** and are parsed to `MicroUsdc`
 * on the way in, because `bigint` does not survive `JSON.stringify`. Every
 * `MicroUsdc` in this file has therefore already been parsed; every string
 * amount is still on the wire.
 */

export type { RefusalCode, WeightReason } from '@tab/protocol'
export {
  BLOCKING_REASONS,
  isBlocking,
  isRetryable,
  REFUSAL_CODES,
  REFUSAL_GUIDANCE,
  WEIGHT_REASON_DETAIL,
  WEIGHT_REASONS,
} from '@tab/protocol'

/* ── spend ──────────────────────────────────────────────────────────────── */

export interface SpendRequest {
  /** The agent's tab. */
  tab: string
  /** The seller's URL, including whatever the seller needs to be paid. */
  url: string
  /** The most this call may cost. */
  /**
   * The most to pay for this one call.
   *
   * Optional: omit it to accept the seller's own quoted price from its x402
   * challenge, which is the usual case — the seller sets the price, so a caller
   * with no budget of its own has nothing to add. Supply it only to spend LESS
   * than the seller asks, which refuses rather than underpays.
   */
  max?: MicroUsdc
  /**
   * Idempotency key.
   *
   * Generated by the client when absent, so a network retry cannot
   * double-spend — the gateway treats it as the hold id. A caller that retries
   * a `TabUnavailableError` MUST reuse the key it sent, which is why the client
   * returns it even on failure.
   */
  idempotencyKey?: string
  init?: { method?: string; headers?: Record<string, string>; body?: string }
}

export interface SpendPaid {
  outcome: 'paid'
  amount: MicroUsdc
  seller: string
  holdId: string
  /** Sequence number of the debit receipt on the HCS topic. */
  receiptSeq: number | null
  /** The seller's own response body, untouched. */
  body: unknown
  elapsedMs: number
}

export interface SpendRefused {
  outcome: 'refused'
  /** The exact rule that fired. This is the product working, not an error. */
  rule: RefusalCode
  reason: string
  /** What the agent should do next. Handling refusal is its main job. */
  guidance: string
  retryable: boolean
  /** The numbers behind the decision, so a caller can show or log them. */
  evidence?: Record<string, string | number>
}

/**
 * Infrastructure failed AFTER the decision to spend — distinct from a refusal
 * on purpose. A refusal means the rail said no; this means nobody said
 * anything, and the caller does not know whether the seller was paid.
 */
export interface SpendFailed {
  outcome: 'failed'
  reason: string
  holdId: string
}

export type SpendResult = SpendPaid | SpendRefused | SpendFailed

/* ── quote ──────────────────────────────────────────────────────────────── */

/**
 * A pre-flight check that reserves nothing.
 *
 * Separate from `spend` because an agent planning a batch needs to know what it
 * can afford without taking headroom it may not use — and a hold taken by a
 * quote would be a hold that never commits, which is exactly the shape the
 * reconciler has to clean up.
 */
export interface Quote {
  tab: string
  affordable: boolean
  available: MicroUsdc
  ceiling: MicroUsdc
  perCallCap: MicroUsdc
  /** Set when not affordable — the rule that would fire. */
  wouldRefuse?: RefusalCode
  reason?: string
}

/* ── state ──────────────────────────────────────────────────────────────── */

export interface TabState {
  tab: string
  /** Signed. Negative means the agent owes. */
  balance: MicroUsdc
  outstanding: MicroUsdc
  holds: MicroUsdc
  available: MicroUsdc
  ceiling: MicroUsdc
  perCallCap: MicroUsdc
  window: number
  entries: number
}

export interface Hold {
  holdId: string
  counterparty: string
  amount: MicroUsdc
  at: string
  expiresAt: string
  status: 'pending' | 'committed' | 'expired'
}

/* ── counterparties ─────────────────────────────────────────────────────── */

/**
 * One counterparty's published independence weight.
 *
 * Read from what the ENGINE published to HCS, never recomputed — the reason
 * codes come from `@tab/protocol`, so the console renders the same vocabulary
 * that is on the topic rather than a translation of it.
 */
export interface CounterpartyWeight {
  counterparty: string
  /** Basis points. 10000 counts in full, 0 blocks the spend. */
  bp: number
  /** Every reason that applied, most severe first. Never empty. */
  reasons: readonly WeightReason[]
  /** True when a reason is fatal — refused, not merely discounted. */
  blocking: boolean
  revenue: MicroUsdc
  /** Share of total revenue, basis points. */
  shareBp: number
  window: number
  at: string
  token?: string

  /*
   * ── the evidence, from the published graph facts ──
   *
   * All optional, and absent means NOT PUBLISHED — never defaulted. A
   * counterparty whose provenance has not been observed is a different fact
   * from one funded by nobody, and a caller must render the difference:
   * inventing a funder here would fabricate the exact evidence these fields
   * exist to expose.
   */
  /** Consensus timestamp of the counterparty's account creation. */
  firstSeen?: string
  /** The account that created this counterparty. */
  funder?: string
  /** Sequence number of the message that established `funder` — cite this. */
  funderSeq?: number
  /**
   * The account that created the TAB.
   *
   * On every row so each is self-contained: `COMMON_FUNDER` is decided by
   * comparing exactly this against `funder`, so a reader holding one row can
   * check the rule without correlating two shapes.
   */
  tabFunder?: string
}

/* ── ceiling ─────────────────────────────────────────────────────────────── */

/** The inputs a ceiling was computed from, as published. */
export interface CeilingInputsView {
  revenue: MicroUsdc
  revenueAttested: MicroUsdc
  revenueUnattested: MicroUsdc
  tier: 'A' | 'B' | 'C' | 'Unrated'
  /** Tier multiple, basis points. 10000 = 1.0x, 0 = no credit at all. */
  multBp: number
  /** Ramp factor, basis points. */
  rampBp: number
  cap: MicroUsdc
  floor: MicroUsdc
  /** Has this tab ever missed a settlement? Zero credit if so, whatever the revenue. */
  defaulted: boolean
}

/** One published ceiling. */
export interface PublishedCeilingView {
  ceiling: MicroUsdc
  /** The formula's result, when the asymmetry rule is holding a growth back. */
  computed?: MicroUsdc
  window: number
  binding: string
  cause: string
  at: string
  model: string
  hash: string
  seq?: number
  inputs: CeilingInputsView
}

/**
 * A tab's ceiling, with the series behind it.
 *
 * `published: false` is the NORMAL state for a tab's first minutes — the engine
 * has not run yet and the starter ceiling is in force. It is not an error, and
 * `enforced` is populated either way, because something is always being
 * enforced.
 */
export interface CeilingView {
  tab: string
  published: boolean
  /**
   * What the fast path is actually checking right now.
   *
   * Normally equal to `current.ceiling`. When it is not, the gap is the most
   * useful number on the screen: the gateway polls the topic every 15s, so a
   * fresh collapse can be published and not yet enforced.
   */
  enforced: MicroUsdc
  current?: PublishedCeilingView
  /** Ascending. The last element is `current`. */
  history: readonly PublishedCeilingView[]
  /** Set when nothing has been published — says what is in force instead. */
  note?: string
}

/* ── settlements ─────────────────────────────────────────────────────────── */

/**
 * One settled window.
 *
 * The gross legs are OPTIONAL because settlements published before those fields
 * existed do not carry them. A reader must render absent as "not published"
 * rather than as `0.0000` — a window whose credits were genuinely zero and one
 * that never recorded its credits are different facts, and showing both as zero
 * invents a netting that was never published.
 */
export interface SettlementView {
  window: number
  at: string
  seq?: number
  /** Signed. Positive paid out to the agent, negative carried as outstanding. */
  net: MicroUsdc
  credits?: MicroUsdc
  debits?: MicroUsdc
  interest?: MicroUsdc
  outstanding?: MicroUsdc
  /** How many receipts collapsed into the one movement. */
  receiptCount?: number
  outcome: 'clean' | 'missed' | 'carried'
  rampFromBp: number
  rampToBp: number
  /** Absent when the window was missed and nothing moved. */
  transactionId?: string
  token?: string
}

/* ── tabs ────────────────────────────────────────────────────────────────── */

/**
 * One tab as the gateway knows it.
 *
 * `tier` and the `published*` fields are OPTIONAL and absent until the engine
 * has published a ceiling for this tab. An unpublished tab has NO tier, which
 * is a different fact from being `Unrated` — guessing one from the balance
 * would put a rating on screen that no topic carries.
 */
export interface TabSummary {
  tab: string
  balance: MicroUsdc
  outstanding: MicroUsdc
  holds: MicroUsdc
  available: MicroUsdc
  /** What the fast path enforces for this tab right now. */
  ceiling: MicroUsdc
  entries: number
  tier?: 'A' | 'B' | 'C' | 'Unrated'
  publishedCeiling?: MicroUsdc
  binding?: string
  cause?: string
  model?: string
  seq?: number
  /**
   * The funding root this tab holds the Starter Tab claim on.
   *
   * Absent means the engine has not registered it yet — NOT that it was denied.
   * The gateway cannot tell those apart: resolving a funding root needs
   * `@tab/graph`, which it may not import.
   */
  registeredRoot?: string
  registeredAt?: string
  registrationSeq?: number
  /**
   * The agent's HCS-14 Universal Agent Identifier.
   *
   * Derived from six canonical fields rather than issued, so anyone can
   * recompute it. Absent on a registration published before it existed.
   */
  uaid?: string
}

/**
 * The tabs this gateway has seen — NOT a registry.
 *
 * `registrationEnforced` describes the RULE, not the data: one Starter Tab per
 * funding root is applied on every engine pass whether or not any root has been
 * claimed yet. A caller asking "has this actually run" should read
 * `rootsClaimed`.
 *
 * It stays on the response rather than being left to a caller's assumption,
 * because a consumer needs to know which rule is in force — and because it was
 * `false` for most of this project's life, when nothing wrote a `register`
 * message at all.
 */
export interface TabList {
  window: number
  registrationEnforced: boolean
  /** How many funding roots have actually been claimed. */
  rootsClaimed: number
  note: string
  tabs: readonly TabSummary[]
}

/* ── receipts ───────────────────────────────────────────────────────────── */

export type ReceiptLeg = 'hold' | 'debit' | 'credit' | 'refusal' | 'repair' | 'settlement'

export interface ReceiptRow {
  leg: ReceiptLeg
  /**
   * The HCS sequence number, when this entry was replayed from a topic.
   *
   * Optional because an entry the gateway created this instant has not been
   * published yet. It is the number to cite in an audit, so the console shows
   * it rather than a counter of its own.
   */
  seq?: number
  /** Hash of the request, when the receipt carried one. Never the request. */
  requestHash?: string
  /** The token these amounts are denominated in. Absent on pre-`tok` receipts. */
  token?: string
  /** Consensus timestamp — the ordering key, and the only one that counts. */
  at: string
  window: number
  counterparty?: string
  /** Signed, as the ledger holds it. */
  amount?: MicroUsdc
  attested?: boolean
  transactionId?: string
  holdId?: string
  rule?: RefusalCode
}
